### PR TITLE
Prevent shell exit after a successful connection

### LINKED ISSUE #103: version 0.9.2 not work
execute mpfshell, open ttyUSB0 , it shows connected and then exit mpfshell. I used to upload files with version 0.9.1 ,it works well.

OS: LinuxMint 20.2
Python 3.8
Pyseiral 3.5

### PR DESCRIPTION
**Pull request by hyx0329**
This pr fix issue introduced by 190bc7557d7c8bf72947c1fff212301962fe031d, close #103.

### CODE REVIEW

**Comment by hyx0329** [comment]
Well I think I should overload the `Cmd.postloop(stop, line)`, as a better approach.

**Comment by skorokithakis** [comment]
Sorry, separate PRs would be better so I can review each one on its own, would you be able to do that?

**Comment by hyx0329** [comment]
okay, leaving only the one relevant commit

**Comment by skorokithakis** [comment]
Thank you!

**Pull request merged**
