### PR TITLE
Change to setuptools, provide mpfshell entrypoint

### PR DESCRIPTION
**Pull request by stlehmann**
Setuptools entry_points make mpfshell more convenient. You can now simply type `$ mpfshell` in the commandline and mpfshell will start.

### CODE REVIEW

**Comment by skorokithakis** [comment]
Is this still relevant? There's an `mpfshell` script which does the same, no?

**Comment by stlehmann** [comment]
Hm, over time some fixes got mixed together in this Pull Request. Sorry for that.

> Is this still relevant? There's an mpfshell script which does the same, no?

Yes, it is still relevant. The mpfshell script can't be used standalone on Windows because it has no file extension. Windows uses file extensions to determine which application to use for running. We could rename it "mpfshell.py" but then we would need to call "mpfshell.py" from the command line to start it. With the Entrypoints approach we have a platform independent solution that allows simply calling "mpfshell" whether you're on Windows, Linux or Mac.

**Comment by skorokithakis** [comment]
Can you split the fixes up? That way we can discuss and merge them separately. I'm all for using `entrypoint` if it doesn't interfere with usage on other platforms, and can merge that immediately.

**Comment by skorokithakis** [comment]
This has been merged in #51, thanks!

**Pull request closed without merging**
